<p>
If you agree with the following rules then click on the 'Accept' button at the bottom of the 
page if not click on the 'Cancel' button.
</p>
<p>
When you register you are required to give a small amount of information, much of which is 
optional, anything you do give must be considered as becoming public information.
</p>
<p>
You agree not to use this forum to post any material which is vulgar, defamatory, inaccurate, 
harassing, hateful, threatening, invading of others privacy, sexually oriented, or violates 
any laws. You also agree that you will not post any copyrighted material that is not owned by 
yourself or the owners of these forums.
</p>
<p>
You remain solely responsible for the content of your messages, and you agree to indemnify and 
hold harmless this forum and their agents with respect to any claim based upon any post you may 
make. We also reserve the right to reveal whatever information we know about you in the event of 
a complaint or legal action arising from any message posted by yourself.</p>
<p>
Although messages posted are not the responsibility of this forum and we are not responsible for 
the content or accuracy of any of these messages, we reserve the right to delete any message for 
any or no reason whatsoever. If you do find any posts are objectionable then please contact 
the forum by e-mail.
</p>
<p>
The Federal Trade Commission's Children's Online Privacy Protection Act of 1998 (COPPA) requires 
that Web Sites are to obtain parental consent before collecting, using, or disclosing personal 
information from children under 13. <b>If you are below 13 then you can NOT use this forum. Do NOT 
register if you are below the age of 13.</b>
</p>
<p>
By registering to use this forum you meet the above criteria and agree to abide by all of the 
above rules and policies.<br>
</p>